### PR TITLE
adding protection against failed double loading when adding keys

### PR DESCRIPTION
**Pull request by slvrspiral**
There is a bug where adding the first key initializes the reCAPTCHA but adding the second causes the validation to show an error when there shouldn't be.  A few if statements prevents this and allows for correct validation.  I also updated some of the messaging to help the user understand what they need to do.

### CODE REVIEW

**Comment by firstred** [comment]
Ahh, so that was the culprit. Thanks!

**Comment by firstred** [comment]
Much better. Thanks a lot for your help!

**Comment by slvrspiral** [comment]
Glad to help.  Am going to look into supporting invisible captcha as well.

**Comment by firstred** [comment]
Ohh that would be really nice! I tried during the beta, but couldn't make it work. It was missing something at the time, but if you manage to activate it, I'd happily accept a PR!

**Pull request merged**
